name: Update R Package

on:
  repository_dispatch:
    types: [update-r-scripts]

jobs:
  update-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout R Package Repo
        uses: actions/checkout@v2
        with:
          ref: main # or your default branch

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install roxygen2
        run: Rscript -e 'install.packages("roxygen2")'

      - name: Checkout cue_expectancy Repo
        uses: actions/checkout@v2
        with:
          repository: jungheejung/cue_expectancy
          path: cue_expectancy

      - name: Copy R Scripts
        run: |
          mkdir -p ./R/
          cp ./cue_expectancy/scripts/step02_R/utils/*.R ./R/

      - name: Document the Package
        run: |
          Rscript -e 'roxygen2::roxygenise()'

      - name: Install Dependencies
        run: |
          Rscript -e 'install.packages("devtools")'
          Rscript -e 'devtools::install_deps(dependencies = TRUE)'

      # - name: Run Tests
      #   run: |
      #     Rscript -e 'devtools::test()'

      - name: Check Package
        run: |
          Rscript -e 'devtools::check()'

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update package with new R scripts" || echo "No changes to commit"
          git push origin HEAD
